steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/inventario-lucense/pedidos-inventario-lucense/deploy-lucense:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/inventario-lucense/pedidos-inventario-lucense/deploy-lucense:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - NOMBRE_SERVICIO
      - --image
      - us-east1-docker.pkg.dev/inventario-lucense/pedidos-inventario-lucense/deploy-lucense:$COMMIT_SHA
      - --region
      - us-east1
      - --platform
      - managed
options:
  logging: CLOUD_LOGGING_ONLY   